server:
  port: 8083

spring:
  application:
    name: payment-service

  jackson:
    time-zone: Asia/Ho_Chi_Minh


  datasource:
    url: jdbc:mysql://globalskill-globalskill.e.aivencloud.com:23246/payment-service?ssl-mode=REQUIRED
    username: avnadmin
    password: ${AIVEN_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: PaymentServicePool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000         # 30 giây
      max-lifetime: 3300000       # 55 phút (an toàn cho DB auto-close 1h)
      connection-timeout: 20000   # 20 giây
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true

sepay:
  webhook-secret: ${WEBHOOK_TOKEN}